version: 2
on:
  workflow_dispatch:

    updates:
      # Maintain dependencies for GitHub Actions
      - package-ecosystem: "github-actions"
        directory: "/"
        schedule:
          interval: "daily"
